// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCewfZ9kFPxYnexgLrulO3Jp1aCMPJ9xcg',
    appId: '1:486059733559:web:0ec3da5d5f48e94cb0c5b2',
    messagingSenderId: '486059733559',
    projectId: 'superstate-970d5',
    authDomain: 'superstate-970d5.firebaseapp.com',
    storageBucket: 'superstate-970d5.appspot.com',
    measurementId: 'G-ZXW3JVMX9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUqkVe_10Ti5rySFL0LTNot2r8BfyEzno',
    appId: '1:486059733559:android:3d0f8787e9f5b28ab0c5b2',
    messagingSenderId: '486059733559',
    projectId: 'superstate-970d5',
    storageBucket: 'superstate-970d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMy8svm3EuHph-K9rztgTrrdHAknxQakQ',
    appId: '1:486059733559:ios:8b21ed1480e4f9cbb0c5b2',
    messagingSenderId: '486059733559',
    projectId: 'superstate-970d5',
    storageBucket: 'superstate-970d5.appspot.com',
    iosBundleId: 'com.superstate.superstate',
  );
}
